version = 0.1
[default.deploy.parameters]
stack_name = "shared-resources"
resolve_s3 = true
s3_prefix = "shared-resources"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
