version: '3.8'
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: ddb-local
    ports:
      - "8000:8000"
    networks:
      dynamodb-local-network: {}

networks:
  dynamodb-local-network:
    name: dynamodb-local-network